EXAMPLE_OUTPUT_FILES = \
  centrimo_example_output_files/centrimo.html \
  centrimo_example_output_files/centrimo.txt \
  centrimo_example_output_files/site_counts.txt \
  dreme_example_output_files/dreme.html \
  dreme_example_output_files/dreme.txt \
  dreme_example_output_files/dreme.xml \
  dreme_example_output_files/m01nc_CCMCRCCC.png \
  dreme_example_output_files/m01rc_GGGYGKGG.png \
  dreme_example_output_files/m02nc_TTATCW.png \
  dreme_example_output_files/m02rc_WGATAA.png \
  dreme_example_output_files/m03nc_CACRCMC.png \
  dreme_example_output_files/m03rc_GKGYGTG.png \
  dreme_example_output_files/m04nc_RARGAAA.png \
  dreme_example_output_files/m04rc_TTTCYTY.png \
  dreme_example_output_files/m05nc_TTTTAWW.png \
  dreme_example_output_files/m05rc_WWTAAAA.png \
  dreme_example_output_files/m06nc_CTCCDCCC.png \
  dreme_example_output_files/m06rc_GGGHGGAG.png \
  dreme_example_output_files/m07nc_ACACRK.png \
  dreme_example_output_files/m07rc_MYGTGT.png \
  dreme_example_output_files/m08nc_MCGCCCW.png \
  dreme_example_output_files/m08rc_WGGGCGK.png \
  dreme_example_output_files/m09nc_TTCTCTB.png \
  dreme_example_output_files/m09rc_VAGAGAA.png \
  dreme_example_output_files/m10nc_AAATRT.png \
  dreme_example_output_files/m10rc_AYATTT.png \
  dreme_example_output_files/m11nc_AKATA.png \
  dreme_example_output_files/m11rc_TATMT.png \
  dreme_example_output_files/m12nc_AAAAHAAA.png \
  dreme_example_output_files/m12rc_TTTDTTTT.png \
  dreme_example_output_files/m13nc_CTGGGRAC.png \
  dreme_example_output_files/m13rc_GTYCCCAG.png \
  dreme_example_output_files/m14nc_SACAGA.png \
  dreme_example_output_files/m14rc_TCTGTS.png \
  fimo_example_output_files/cisml.css \
  fimo_example_output_files/cisml.xml \
  fimo_example_output_files/fimo-to-html.xsl \
  fimo_example_output_files/fimo.gff \
  fimo_example_output_files/fimo.html \
  fimo_example_output_files/fimo.txt \
  fimo_example_output_files/fimo.xml \
  glam2_example_output_files/glam2.html \
  glam2_example_output_files/glam2.meme \
  glam2_example_output_files/glam2.txt \
  glam2_example_output_files/logo1.eps \
  glam2_example_output_files/logo1.png \
  glam2_example_output_files/logo10.eps \
  glam2_example_output_files/logo10.png \
  glam2_example_output_files/logo2.eps \
  glam2_example_output_files/logo2.png \
  glam2_example_output_files/logo3.eps \
  glam2_example_output_files/logo3.png \
  glam2_example_output_files/logo4.eps \
  glam2_example_output_files/logo4.png \
  glam2_example_output_files/logo5.eps \
  glam2_example_output_files/logo5.png \
  glam2_example_output_files/logo6.eps \
  glam2_example_output_files/logo6.png \
  glam2_example_output_files/logo7.eps \
  glam2_example_output_files/logo7.png \
  glam2_example_output_files/logo8.eps \
  glam2_example_output_files/logo8.png \
  glam2_example_output_files/logo9.eps \
  glam2_example_output_files/logo9.png \
  glam2_example_output_files/logo_ssc1.eps \
  glam2_example_output_files/logo_ssc1.png \
  glam2_example_output_files/logo_ssc10.eps \
  glam2_example_output_files/logo_ssc10.png \
  glam2_example_output_files/logo_ssc2.eps \
  glam2_example_output_files/logo_ssc2.png \
  glam2_example_output_files/logo_ssc3.eps \
  glam2_example_output_files/logo_ssc3.png \
  glam2_example_output_files/logo_ssc4.eps \
  glam2_example_output_files/logo_ssc4.png \
  glam2_example_output_files/logo_ssc5.eps \
  glam2_example_output_files/logo_ssc5.png \
  glam2_example_output_files/logo_ssc6.eps \
  glam2_example_output_files/logo_ssc6.png \
  glam2_example_output_files/logo_ssc7.eps \
  glam2_example_output_files/logo_ssc7.png \
  glam2_example_output_files/logo_ssc8.eps \
  glam2_example_output_files/logo_ssc8.png \
  glam2_example_output_files/logo_ssc9.eps \
  glam2_example_output_files/logo_ssc9.png \
  glam2scan_example_output_files/glam2scan.html \
  glam2scan_example_output_files/glam2scan.txt \
  mast_example_output_files/mast.html \
  mast_example_output_files/mast.txt \
  mast_example_output_files/mast.xml \
  mcast_example_output_files/block-diagram.xsl \
  mcast_example_output_files/cisml.xml \
  mcast_example_output_files/mcast-to-html.xsl \
  mcast_example_output_files/mcast-to-text.xsl \
  mcast_example_output_files/mcast.html \
  mcast_example_output_files/mcast.txt \
  mcast_example_output_files/mcast.xml \
  mcast_example_output_files/meme.css.xsl \
  meme_example_output_files/help.gif \
  meme_example_output_files/logo1.eps \
  meme_example_output_files/logo1.png \
  meme_example_output_files/logo2.eps \
  meme_example_output_files/logo2.png \
  meme_example_output_files/logo3.eps \
  meme_example_output_files/logo3.png \
  meme_example_output_files/logo_rc1.eps \
  meme_example_output_files/logo_rc1.png \
  meme_example_output_files/logo_rc2.eps \
  meme_example_output_files/logo_rc2.png \
  meme_example_output_files/logo_rc3.eps \
  meme_example_output_files/logo_rc3.png \
  meme_example_output_files/meme.html \
  meme_example_output_files/meme.txt \
  meme_example_output_files/meme.xml \
  memechip_example_output_files/align_msgs.txt \
  memechip_example_output_files/background \
  memechip_example_output_files/combined.meme \
  memechip_example_output_files/index.html \
  memechip_example_output_files/motif_alignment.txt \
  memechip_example_output_files/progress_log.txt \
  memechip_example_output_files/sample-dna-Klf1.fa \
  memechip_example_output_files/seqs-centered \
  memechip_example_output_files/seqs-discarded \
  memechip_example_output_files/seqs-sampled \
  memechip_example_output_files/seqs-shuffled \
  memechip_example_output_files/meme_tomtom_out/tomtom.html \
  memechip_example_output_files/meme_tomtom_out/tomtom.txt \
  memechip_example_output_files/meme_tomtom_out/tomtom.xml \
  memechip_example_output_files/meme_out/help.gif \
  memechip_example_output_files/meme_out/logo1.eps \
  memechip_example_output_files/meme_out/logo1.png \
  memechip_example_output_files/meme_out/logo2.eps \
  memechip_example_output_files/meme_out/logo2.png \
  memechip_example_output_files/meme_out/logo3.eps \
  memechip_example_output_files/meme_out/logo3.png \
  memechip_example_output_files/meme_out/logo_rc1.eps \
  memechip_example_output_files/meme_out/logo_rc1.png \
  memechip_example_output_files/meme_out/logo_rc2.eps \
  memechip_example_output_files/meme_out/logo_rc2.png \
  memechip_example_output_files/meme_out/logo_rc3.eps \
  memechip_example_output_files/meme_out/logo_rc3.png \
  memechip_example_output_files/meme_out/meme.html \
  memechip_example_output_files/meme_out/meme.txt \
  memechip_example_output_files/meme_out/meme.xml \
  memechip_example_output_files/dreme_tomtom_out/tomtom.html \
  memechip_example_output_files/dreme_tomtom_out/tomtom.txt \
  memechip_example_output_files/dreme_tomtom_out/tomtom.xml \
  memechip_example_output_files/dreme_out/dreme.html \
  memechip_example_output_files/dreme_out/dreme.txt \
  memechip_example_output_files/dreme_out/dreme.xml \
  memechip_example_output_files/dreme_out/m01nc_MCRCCCW.png \
  memechip_example_output_files/dreme_out/m01rc_WGGGYGK.png \
  memechip_example_output_files/dreme_out/m02nc_TTATCW.png \
  memechip_example_output_files/dreme_out/m02rc_WGATAA.png \
  memechip_example_output_files/dreme_out/m03nc_ARATA.png \
  memechip_example_output_files/dreme_out/m03rc_TATYT.png \
  memechip_example_output_files/dreme_out/m04nc_CCMCACCC.png \
  memechip_example_output_files/dreme_out/m04rc_GGGTGKGG.png \
  memechip_example_output_files/dreme_out/m05nc_ACAGMTG.png \
  memechip_example_output_files/dreme_out/m05rc_CAKCTGT.png \
  memechip_example_output_files/centrimo_out/centrimo.html \
  memechip_example_output_files/centrimo_out/centrimo.txt \
  memechip_example_output_files/centrimo_out/site_counts.txt \
  spamo_example_output_files/hist_MA0039.2_db1_MA0035.2.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0037.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0057.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0140.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0217.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0289.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0300.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0307.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0309.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0429.1.png \
  spamo_example_output_files/spamo.html \
  spamo_example_output_files/spamo.xml \
  tomtom_example_output_files/tomtom.html \
  tomtom_example_output_files/tomtom.txt \
  tomtom_example_output_files/tomtom.xml
