EXAMPLE_OUTPUT_FILES = \
  ame_example_output_files/ame.html \
  ame_example_output_files/ame.txt \
  centrimo_example_output_files/centrimo.html \
  centrimo_example_output_files/centrimo.txt \
  centrimo_example_output_files/site_counts.txt \
  dreme_example_output_files/dreme.html \
  dreme_example_output_files/dreme.txt \
  dreme_example_output_files/dreme.xml \
  dreme_example_output_files/m01nc_CCMCRCCC.png \
  dreme_example_output_files/m01rc_GGGYGKGG.png \
  dreme_example_output_files/m02nc_BTTATCW.png \
  dreme_example_output_files/m02rc_WGATAAV.png \
  dreme_example_output_files/m03nc_MCRCCCA.png \
  dreme_example_output_files/m03rc_TGGGYGK.png \
  dreme_example_output_files/m04nc_RARGAAA.png \
  dreme_example_output_files/m04rc_TTTCYTY.png \
  dreme_example_output_files/m05nc_AKAAAM.png \
  dreme_example_output_files/m05rc_KTTTMT.png \
  dreme_example_output_files/m06nc_CTGTSTS.png \
  dreme_example_output_files/m06rc_SASACAG.png \
  dreme_example_output_files/m07nc_AGGGCGK.png \
  dreme_example_output_files/m07rc_MCGCCCT.png \
  dreme_example_output_files/m08nc_CCTKCCY.png \
  dreme_example_output_files/m08rc_RGGMAGG.png \
  dreme_example_output_files/m09nc_TTAAAAW.png \
  dreme_example_output_files/m09rc_WTTTTAA.png \
  dreme_example_output_files/m10nc_AAATAH.png \
  dreme_example_output_files/m10rc_DTATTT.png \
  dreme_example_output_files/m11nc_CATYTCC.png \
  dreme_example_output_files/m11rc_GGARATG.png \
  dreme_example_output_files/m12nc_CAGMCAC.png \
  dreme_example_output_files/m12rc_GTGKCTG.png \
  dreme_example_output_files/m13nc_CACAGY.png \
  dreme_example_output_files/m13rc_RCTGTG.png \
  dreme_example_output_files/m14nc_CTGGRGA.png \
  dreme_example_output_files/m14rc_TCYCCAG.png \
  dreme_example_output_files/m15nc_SACGTGA.png \
  dreme_example_output_files/m15rc_TCACGTS.png \
  fimo_example_output_files/cisml.css \
  fimo_example_output_files/cisml.xml \
  fimo_example_output_files/fimo-to-html.xsl \
  fimo_example_output_files/fimo.gff \
  fimo_example_output_files/fimo.html \
  fimo_example_output_files/fimo.txt \
  fimo_example_output_files/fimo.xml \
  glam2_example_output_files/glam2.html \
  glam2_example_output_files/glam2.meme \
  glam2_example_output_files/glam2.txt \
  glam2_example_output_files/logo1.eps \
  glam2_example_output_files/logo1.png \
  glam2_example_output_files/logo10.eps \
  glam2_example_output_files/logo10.png \
  glam2_example_output_files/logo2.eps \
  glam2_example_output_files/logo2.png \
  glam2_example_output_files/logo3.eps \
  glam2_example_output_files/logo3.png \
  glam2_example_output_files/logo4.eps \
  glam2_example_output_files/logo4.png \
  glam2_example_output_files/logo5.eps \
  glam2_example_output_files/logo5.png \
  glam2_example_output_files/logo6.eps \
  glam2_example_output_files/logo6.png \
  glam2_example_output_files/logo7.eps \
  glam2_example_output_files/logo7.png \
  glam2_example_output_files/logo8.eps \
  glam2_example_output_files/logo8.png \
  glam2_example_output_files/logo9.eps \
  glam2_example_output_files/logo9.png \
  glam2_example_output_files/logo_ssc1.eps \
  glam2_example_output_files/logo_ssc1.png \
  glam2_example_output_files/logo_ssc10.eps \
  glam2_example_output_files/logo_ssc10.png \
  glam2_example_output_files/logo_ssc2.eps \
  glam2_example_output_files/logo_ssc2.png \
  glam2_example_output_files/logo_ssc3.eps \
  glam2_example_output_files/logo_ssc3.png \
  glam2_example_output_files/logo_ssc4.eps \
  glam2_example_output_files/logo_ssc4.png \
  glam2_example_output_files/logo_ssc5.eps \
  glam2_example_output_files/logo_ssc5.png \
  glam2_example_output_files/logo_ssc6.eps \
  glam2_example_output_files/logo_ssc6.png \
  glam2_example_output_files/logo_ssc7.eps \
  glam2_example_output_files/logo_ssc7.png \
  glam2_example_output_files/logo_ssc8.eps \
  glam2_example_output_files/logo_ssc8.png \
  glam2_example_output_files/logo_ssc9.eps \
  glam2_example_output_files/logo_ssc9.png \
  glam2scan_example_output_files/glam2scan.html \
  glam2scan_example_output_files/glam2scan.txt \
  gomo_example_output_files/gomo.html \
  gomo_example_output_files/gomo.xml \
  gomo_example_output_files/res/logocrp.png \
  gomo_example_output_files/res/logonagC.png \
  gomo_example_output_files/res/logonarP.png \
  mast_example_output_files/mast.html \
  mast_example_output_files/mast.txt \
  mast_example_output_files/mast.xml \
  mcast_example_output_files/block-diagram.xsl \
  mcast_example_output_files/cisml.xml \
  mcast_example_output_files/constants.xsl \
  mcast_example_output_files/mcast-to-bed.xsl \
  mcast_example_output_files/mcast-to-html.xsl \
  mcast_example_output_files/mcast-to-text.xsl \
  mcast_example_output_files/mcast.bed \
  mcast_example_output_files/mcast.html \
  mcast_example_output_files/mcast.txt \
  mcast_example_output_files/mcast.xml \
  mcast_example_output_files/meme.css.xsl \
  meme_example_output_files/logo1.eps \
  meme_example_output_files/logo1.png \
  meme_example_output_files/logo2.eps \
  meme_example_output_files/logo2.png \
  meme_example_output_files/logo3.eps \
  meme_example_output_files/logo3.png \
  meme_example_output_files/logo_rc1.eps \
  meme_example_output_files/logo_rc1.png \
  meme_example_output_files/logo_rc2.eps \
  meme_example_output_files/logo_rc2.png \
  meme_example_output_files/logo_rc3.eps \
  meme_example_output_files/logo_rc3.png \
  meme_example_output_files/meme.html \
  meme_example_output_files/meme.txt \
  meme_example_output_files/meme.xml \
  memechip_example_output_files/align_msgs.txt \
  memechip_example_output_files/background \
  memechip_example_output_files/combined.meme \
  memechip_example_output_files/index.html \
  memechip_example_output_files/meme_msgs.txt \
  memechip_example_output_files/motif_alignment.txt \
  memechip_example_output_files/progress_log.txt \
  memechip_example_output_files/sample-dna-Klf1.fa \
  memechip_example_output_files/seqs-centered \
  memechip_example_output_files/seqs-discarded \
  memechip_example_output_files/seqs-sampled \
  memechip_example_output_files/seqs-shuffled \
  memechip_example_output_files/spamo_out_7/spamo.html \
  memechip_example_output_files/spamo_out_7/spamo.xml \
  memechip_example_output_files/spamo_out_6/spamo.html \
  memechip_example_output_files/spamo_out_6/spamo.xml \
  memechip_example_output_files/spamo_out_5/spamo.html \
  memechip_example_output_files/spamo_out_5/spamo.xml \
  memechip_example_output_files/spamo_out_4/spamo.html \
  memechip_example_output_files/spamo_out_4/spamo.xml \
  memechip_example_output_files/spamo_out_3/spamo.html \
  memechip_example_output_files/spamo_out_3/spamo.xml \
  memechip_example_output_files/spamo_out_2/spamo.html \
  memechip_example_output_files/spamo_out_2/spamo.xml \
  memechip_example_output_files/spamo_out_1/spamo.html \
  memechip_example_output_files/spamo_out_1/spamo.xml \
  memechip_example_output_files/fimo_out_7/cisml.css \
  memechip_example_output_files/fimo_out_7/cisml.xml \
  memechip_example_output_files/fimo_out_7/fimo-to-html.xsl \
  memechip_example_output_files/fimo_out_7/fimo.gff \
  memechip_example_output_files/fimo_out_7/fimo.html \
  memechip_example_output_files/fimo_out_7/fimo.txt \
  memechip_example_output_files/fimo_out_7/fimo.xml \
  memechip_example_output_files/fimo_out_6/cisml.css \
  memechip_example_output_files/fimo_out_6/cisml.xml \
  memechip_example_output_files/fimo_out_6/fimo-to-html.xsl \
  memechip_example_output_files/fimo_out_6/fimo.gff \
  memechip_example_output_files/fimo_out_6/fimo.html \
  memechip_example_output_files/fimo_out_6/fimo.txt \
  memechip_example_output_files/fimo_out_6/fimo.xml \
  memechip_example_output_files/fimo_out_5/cisml.css \
  memechip_example_output_files/fimo_out_5/cisml.xml \
  memechip_example_output_files/fimo_out_5/fimo-to-html.xsl \
  memechip_example_output_files/fimo_out_5/fimo.gff \
  memechip_example_output_files/fimo_out_5/fimo.html \
  memechip_example_output_files/fimo_out_5/fimo.txt \
  memechip_example_output_files/fimo_out_5/fimo.xml \
  memechip_example_output_files/fimo_out_4/cisml.css \
  memechip_example_output_files/fimo_out_4/cisml.xml \
  memechip_example_output_files/fimo_out_4/fimo-to-html.xsl \
  memechip_example_output_files/fimo_out_4/fimo.gff \
  memechip_example_output_files/fimo_out_4/fimo.html \
  memechip_example_output_files/fimo_out_4/fimo.txt \
  memechip_example_output_files/fimo_out_4/fimo.xml \
  memechip_example_output_files/fimo_out_3/cisml.css \
  memechip_example_output_files/fimo_out_3/cisml.xml \
  memechip_example_output_files/fimo_out_3/fimo-to-html.xsl \
  memechip_example_output_files/fimo_out_3/fimo.gff \
  memechip_example_output_files/fimo_out_3/fimo.html \
  memechip_example_output_files/fimo_out_3/fimo.txt \
  memechip_example_output_files/fimo_out_3/fimo.xml \
  memechip_example_output_files/fimo_out_2/cisml.css \
  memechip_example_output_files/fimo_out_2/cisml.xml \
  memechip_example_output_files/fimo_out_2/fimo-to-html.xsl \
  memechip_example_output_files/fimo_out_2/fimo.gff \
  memechip_example_output_files/fimo_out_2/fimo.html \
  memechip_example_output_files/fimo_out_2/fimo.txt \
  memechip_example_output_files/fimo_out_2/fimo.xml \
  memechip_example_output_files/fimo_out_1/cisml.css \
  memechip_example_output_files/fimo_out_1/cisml.xml \
  memechip_example_output_files/fimo_out_1/fimo-to-html.xsl \
  memechip_example_output_files/fimo_out_1/fimo.gff \
  memechip_example_output_files/fimo_out_1/fimo.html \
  memechip_example_output_files/fimo_out_1/fimo.txt \
  memechip_example_output_files/fimo_out_1/fimo.xml \
  memechip_example_output_files/dreme_tomtom_out/tomtom.html \
  memechip_example_output_files/dreme_tomtom_out/tomtom.txt \
  memechip_example_output_files/dreme_tomtom_out/tomtom.xml \
  memechip_example_output_files/dreme_out/dreme.html \
  memechip_example_output_files/dreme_out/dreme.txt \
  memechip_example_output_files/dreme_out/dreme.xml \
  memechip_example_output_files/dreme_out/m01nc_GGGYGK.png \
  memechip_example_output_files/dreme_out/m01rc_MCRCCC.png \
  memechip_example_output_files/dreme_out/m02nc_TTATCW.png \
  memechip_example_output_files/dreme_out/m02rc_WGATAA.png \
  memechip_example_output_files/dreme_out/m03nc_AGAWA.png \
  memechip_example_output_files/dreme_out/m03rc_TWTCT.png \
  memechip_example_output_files/centrimo_out/centrimo.html \
  memechip_example_output_files/centrimo_out/centrimo.txt \
  memechip_example_output_files/centrimo_out/site_counts.txt \
  spamo_example_output_files/hist_MA0039.2_db1_MA0013.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0035.2.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0037.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0140.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0217.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0289.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0300.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0307.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0309.1.png \
  spamo_example_output_files/hist_MA0039.2_db1_MA0429.1.png \
  spamo_example_output_files/spamo.html \
  spamo_example_output_files/spamo.xml \
  tomtom_example_output_files/tomtom.html \
  tomtom_example_output_files/tomtom.txt \
  tomtom_example_output_files/tomtom.xml
