WEBSITE_FILES = website/alternate/doc/js/menu-path.js \
  website/canvas-test.html \
  website/css/component_bfile.css \
  website/css/component_glam2motifs.css \
  website/css/component_motifs.css \
  website/css/component_sequences.css \
  website/css/fasta-debug.css \
  website/css/status.css \
  website/css/tomtom.css \
  website/images/euclidean-eq.png \
  website/images/logo_alignment.png \
  website/images/pearson-eq.png \
  website/images/sandelin-eq.png \
  website/index.html \
  website/js/ame.js \
  website/js/bg_parser.js \
  website/js/centrimo.js \
  website/js/component_bfile.js \
  website/js/component_glam2motifs.js \
  website/js/component_motifs.js \
  website/js/component_sequences.js \
  website/js/dreme.js \
  website/js/fasta-debug.js \
  website/js/fimo.js \
  website/js/glam2.js \
  website/js/glam2scan.js \
  website/js/gomo.js \
  website/js/mast.js \
  website/js/mcast.js \
  website/js/meme-chip.js \
  website/js/meme.js \
  website/js/menu-path.js \
  website/js/motif_parser.js \
  website/js/selectdb.js \
  website/js/site.js \
  website/js/spamo.js \
  website/js/status.js \
  website/js/tomtom.js \
  website/js/wgxpath.install.js \
  website/lib/JSAP-2.1.jar \
  website/lib/JSAP.LICENSE \
  website/lib/RSATWS.jar \
  website/lib/axis.LICENSE \
  website/lib/axis.jar \
  website/lib/cog-axis.jar \
  website/lib/cog-jglobus.jar \
  website/lib/cog.LICENSE \
  website/lib/commons-discovery-0.5.jar \
  website/lib/commons-discovery.LICENSE \
  website/lib/commons-discovery.NOTICE \
  website/lib/commons-io-2.4.jar \
  website/lib/commons-io.LICENSE \
  website/lib/commons-io.NOTICE \
  website/lib/commons-logging-1.1.3.jar \
  website/lib/commons-logging.LICENSE \
  website/lib/commons-logging.NOTICE \
  website/lib/commons-net-3.3.jar \
  website/lib/commons-net.LICENSE \
  website/lib/commons-net.NOTICE \
  website/lib/javamail-1.4.3.jar \
  website/lib/jaxrpc.jar \
  website/lib/jsoup-1.7.3.jar \
  website/lib/jsoup.LICENSE \
  website/lib/jtar-1.1.jar \
  website/lib/jtar.LICENSE \
  website/lib/opal-ws-2.5.jar \
  website/lib/sqlite-jdbc-3.7.2.jar \
  website/lib/sqlite-jdbc.LICENSE \
  website/lib/wsdl4j-1.6.3.jar \
  website/lib/wsdl4j.LICENSE \
  website/src/au/edu/uq/imb/memesuite/data/Alphabet.java \
  website/src/au/edu/uq/imb/memesuite/data/Background.java \
  website/src/au/edu/uq/imb/memesuite/data/MemeSuiteProperties.java \
  website/src/au/edu/uq/imb/memesuite/data/MotifDataSource.java \
  website/src/au/edu/uq/imb/memesuite/data/MotifInfo.java \
  website/src/au/edu/uq/imb/memesuite/data/MotifStats.java \
  website/src/au/edu/uq/imb/memesuite/data/NamedFileDataSource.java \
  website/src/au/edu/uq/imb/memesuite/data/SequenceDataSource.java \
  website/src/au/edu/uq/imb/memesuite/data/SequenceInfo.java \
  website/src/au/edu/uq/imb/memesuite/data/SequenceStats.java \
  website/src/au/edu/uq/imb/memesuite/db/Category.java \
  website/src/au/edu/uq/imb/memesuite/db/DBList.java \
  website/src/au/edu/uq/imb/memesuite/db/GomoDB.java \
  website/src/au/edu/uq/imb/memesuite/db/GomoDBList.java \
  website/src/au/edu/uq/imb/memesuite/db/GomoDBSecondary.java \
  website/src/au/edu/uq/imb/memesuite/db/Listing.java \
  website/src/au/edu/uq/imb/memesuite/db/MotifDB.java \
  website/src/au/edu/uq/imb/memesuite/db/MotifDBFile.java \
  website/src/au/edu/uq/imb/memesuite/db/MotifDBList.java \
  website/src/au/edu/uq/imb/memesuite/db/SQL.java \
  website/src/au/edu/uq/imb/memesuite/db/SequenceDB.java \
  website/src/au/edu/uq/imb/memesuite/db/SequenceDBList.java \
  website/src/au/edu/uq/imb/memesuite/db/SequenceVersion.java \
  website/src/au/edu/uq/imb/memesuite/io/fasta/FastaException.java \
  website/src/au/edu/uq/imb/memesuite/io/fasta/FastaHandler.java \
  website/src/au/edu/uq/imb/memesuite/io/fasta/FastaParseException.java \
  website/src/au/edu/uq/imb/memesuite/io/fasta/FastaParser.java \
  website/src/au/edu/uq/imb/memesuite/io/fasta/FastaWriter.java \
  website/src/au/edu/uq/imb/memesuite/io/html/HDataHandler.java \
  website/src/au/edu/uq/imb/memesuite/io/html/HDataHandlerAdapter.java \
  website/src/au/edu/uq/imb/memesuite/io/html/HDataParser.java \
  website/src/au/edu/uq/imb/memesuite/io/json/JsonHandler.java \
  website/src/au/edu/uq/imb/memesuite/io/json/JsonHandlerAdapter.java \
  website/src/au/edu/uq/imb/memesuite/io/json/JsonParser.java \
  website/src/au/edu/uq/imb/memesuite/io/json/JsonToken.java \
  website/src/au/edu/uq/imb/memesuite/io/json/JsonType.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Ame.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Centrimo.java \
  website/src/au/edu/uq/imb/memesuite/servlet/ConfigurationLoader.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Dreme.java \
  website/src/au/edu/uq/imb/memesuite/servlet/EchoFile.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Fimo.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Glam2.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Glam2Request.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Glam2scan.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Gomo.java \
  website/src/au/edu/uq/imb/memesuite/servlet/JobStatus.java \
  website/src/au/edu/uq/imb/memesuite/servlet/LogoRequest.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Mast.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Mcast.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Meme.java \
  website/src/au/edu/uq/imb/memesuite/servlet/MemeRequest.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Memechip.java \
  website/src/au/edu/uq/imb/memesuite/servlet/PermanentRedirect.java \
  website/src/au/edu/uq/imb/memesuite/servlet/ShowGomoDBs.java \
  website/src/au/edu/uq/imb/memesuite/servlet/ShowMotifDBs.java \
  website/src/au/edu/uq/imb/memesuite/servlet/ShowSequenceDBs.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Spamo.java \
  website/src/au/edu/uq/imb/memesuite/servlet/SubmitJob.java \
  website/src/au/edu/uq/imb/memesuite/servlet/Tomtom.java \
  website/src/au/edu/uq/imb/memesuite/servlet/TomtomRequest.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentAdvancedOptions.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentBfile.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentFooter.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentGlam2Motifs.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentGomo.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentHeader.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentJobDetails.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentMotifs.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentSequences.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/ComponentSubmitReset.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/FeedbackFastaWriter.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/FeedbackHandler.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/Glam2Validator.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/MotifValidator.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/PageComponent.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/StreamCopier.java \
  website/src/au/edu/uq/imb/memesuite/servlet/util/WebUtils.java \
  website/src/au/edu/uq/imb/memesuite/template/HTMLSub.java \
  website/src/au/edu/uq/imb/memesuite/template/HTMLTemplate.java \
  website/src/au/edu/uq/imb/memesuite/template/HTMLTemplateCache.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/AbstractFtpSource.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/EPDUpdater.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/EPDUpdater.properties \
  website/src/au/edu/uq/imb/memesuite/updatedb/EnsemblUpdater.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/FtpFileListUpdater.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/FtpFileListUpdater.properties \
  website/src/au/edu/uq/imb/memesuite/updatedb/FtpSource.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/GenbankUpdater.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/GenbankUpdater.properties \
  website/src/au/edu/uq/imb/memesuite/updatedb/PatternFileFilter.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/RsatUpdater.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/RsatUpdater.properties \
  website/src/au/edu/uq/imb/memesuite/updatedb/SequenceProcessor.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/SequenceUpdater.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/Source.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/UCSCGenomeUpdater.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/UpdateSequenceDB.java \
  website/src/au/edu/uq/imb/memesuite/updatedb/UpdateSequenceDB.properties \
  website/src/au/edu/uq/imb/memesuite/util/BMString.java \
  website/src/au/edu/uq/imb/memesuite/util/FileCoord.java \
  website/src/au/edu/uq/imb/memesuite/util/GlobFilter.java \
  website/src/au/edu/uq/imb/memesuite/util/JsonWr.java \
  website/src/au/edu/uq/imb/memesuite/util/MultiSourceStatus.java \
  website/src/au/edu/uq/imb/memesuite/util/Progress.java \
  website/src/au/edu/uq/imb/memesuite/util/SampleStats.java \
  website/src/au/edu/uq/imb/memesuite/util/SemanticVersion.java \
  website/templates/ame.tmpl \
  website/templates/ame_verify.tmpl \
  website/templates/centrimo.tmpl \
  website/templates/centrimo_verify.tmpl \
  website/templates/component_adv_btn.tmpl \
  website/templates/component_bfile.tmpl \
  website/templates/component_footer.tmpl \
  website/templates/component_glam2motifs.tmpl \
  website/templates/component_gomo.tmpl \
  website/templates/component_header.tmpl \
  website/templates/component_job_details.tmpl \
  website/templates/component_motifs.tmpl \
  website/templates/component_sequences.tmpl \
  website/templates/component_submit_reset.tmpl \
  website/templates/dreme.tmpl \
  website/templates/dreme_verify.tmpl \
  website/templates/email.tmpl \
  website/templates/fimo.tmpl \
  website/templates/fimo_verify.tmpl \
  website/templates/glam2.tmpl \
  website/templates/glam2_verify.tmpl \
  website/templates/glam2scan.tmpl \
  website/templates/glam2scan_verify.tmpl \
  website/templates/gomo.tmpl \
  website/templates/gomo_verify.tmpl \
  website/templates/mast.tmpl \
  website/templates/mast_verify.tmpl \
  website/templates/mcast.tmpl \
  website/templates/mcast_verify.tmpl \
  website/templates/meme-chip.tmpl \
  website/templates/meme-chip_verify.tmpl \
  website/templates/meme.tmpl \
  website/templates/meme_verify.tmpl \
  website/templates/request_redirect.tmpl \
  website/templates/show_gomo_dbs.tmpl \
  website/templates/show_motif_dbs.tmpl \
  website/templates/show_sequence_dbs.tmpl \
  website/templates/spamo.tmpl \
  website/templates/spamo_verify.tmpl \
  website/templates/status.tmpl \
  website/templates/tomtom.tmpl \
  website/templates/tomtom_verify.tmpl \
  website/templates/verify.tmpl \
  website/templates/whine.tmpl \
  website/web.xml